services:
  php-box:
    container_name: php-box
    environment:
    - TZ=Asia/Shanghai
    - ADMIN_USER=admin
    - ADMIN_PASS=admin
    - PHP_DEFAULT=php84
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
      - CMD-SHELL
      - wget -qO- http://127.0.0.1:80/healthz >/dev/null 2>&1 && wget -qO- http://127.0.0.1:8080/ >/dev/null 2>&1
      timeout: 5s
    image: ghcr.io/kanchairen-d/php-box:latest
    restart: unless-stopped
    ports:
      - 5080:80
      - 5090:8080
    volumes:
      - ./repo:/var/www/repo
      - ./nginx/php-box.conf:/etc/nginx/http.d/php-box.conf
      - ./nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./html/index.html:/var/www/html/index.html
      - ./html/app.js:/var/www/html/app.js
